//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.24 at 08:31:16 PM BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soapcoursemanagement.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soapcoursemanagement.courses;
